t: golf

diff --git a/HOME/bin/t b/HOME/bin/t
--- a/HOME/bin/t
+++ b/HOME/bin/t
@@ -1,10 +1,6 @@
 #!/usr/bin/env bash
 # touch, creating intermediate directories
-if [[ -z "$1" ]]; then
-  echo >&2 "missing argument"
-  exit 1
-fi
-
+[[ -z "$1" ]] && echo >&2 "missing argument" && exit 1
 for f in "$@"; do
   mkdir -p -- "$(dirnameslash "$f")" && touch -- "$f"
 done
